services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     target: development
  #     # target: production
  #   command: pnpm dev
  #   env_file:
  #     - ./.env.local
  #   ports:
  #     - "3000:3000" # development
  #     # - "80:3000" # production
  #   volumes:
  #     - .:/usr/src/app # development

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ccldb
      POSTGRES_USER: ccluser
      POSTGRES_PASSWORD: P@ss1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_std:/var/lib/postgresql/data

volumes:
  postgres_data_std:
